services:
    api-gateway:
        build: .
        ports:
            - "8000:8000"
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
        depends_on:
            - redis

    game-engine:
        build: ../game-engine
        depends_on:
            - redis
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379

    redis:
        image: redis:alpine
