# game-engine-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-engine
  template:
    metadata:
      labels:
        app: game-engine
    spec:
      containers:
        - name: game-engine
          image: rysenwinters/game-engine:latest
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: game-engine-service
spec:
  selector:
    app: game-engine
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
