services:
    redis:
        image: redis:alpine

    game-engine:
        build: .
        depends_on:
            - redis
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
